pipeline {
    agent any
    
    environment {
        DOCKER_REGISTRY = 'aaqibmd123' 
        IMAGE_NAME = 'assignment'  
        KUBE_NAMESPACE = 'assignment_ns'      
        KUBE_CONFIG_PATH = '~/.kube/config'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/aaqibmd123/Shgardi_assignment'  
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    def buildNumber = env.BUILD_NUMBER
                    sh """
                        docker build -t ${DOCKER_REGISTRY}/${IMAGE_NAME}:${buildNumber} .
                    """
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: DOCKER_CREDENTIALS, usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                        sh """
                            echo \$DOCKER_PASSWORD | docker login -u \$DOCKER_USERNAME --password-stdin
                            docker push ${DOCKER_REGISTRY}/${IMAGE_NAME}:${env.BUILD_NUMBER}
                        """
                    }
                }
            }
        }

         stage('Deploy to Kubernetes') {
            steps {
                script {
                    withEnv(["KUBECONFIG=${KUBE_CONFIG_PATH}"]) {
                        def deploymentExists = sh(script: "kubectl get deployment ${IMAGE_NAME} -n ${KUBE_NAMESPACE} --ignore-not-found=true", returnStatus: true)
                        
                        if (deploymentExists == 0) {
                            echo "Deployment exists. Updating image..."
                            sh """
                                kubectl set image deployment/${IMAGE_NAME} ${IMAGE_NAME}=${DOCKER_REGISTRY}/${IMAGE_NAME}:${env.BUILD_NUMBER} -n ${KUBE_NAMESPACE}
                            """
                        } else {
                            echo "Deployment does not exist. Creating new deployment..."
                            sh """
                                kubectl create deployment ${IMAGE_NAME} --image=${DOCKER_REGISTRY}/${IMAGE_NAME}:${env.BUILD_NUMBER} -n ${KUBE_NAMESPACE}
                            """
                        }
                    }
                }
            }
         }

        post {
            success {
                echo "Pipeline succeeded!"
            }
            failure {
                echo "Pipeline failed!"
            }
        }
    }
}

